using static System.Net.Mime.MediaTypeNames;

namespace MarvelMultiverse.Constants;

public static class TraitNames
{
    public const string Abrasive = "Abrasive";
    public const string Anathema = "Anathema";
    public const string Audience = "Audience";
    public const string BattleReady = "Battle Ready";
    public const string Beguiling = "Beguiling";
    public const string Berserker = "Berserker";
    public const string Big = "Big";
    public const string Bloodthirsty = "Bloodthirsty";
    public const string BreatheDifferent = "Breathe Different";
    public const string Clinician = "Clinician";
    public const string CombatExpert = "Combat Expert";
    public const string CombatReflexes = "Combat Reflexes";
    public const string Connections = "Connections";
    public const string Dealmaker = "Dealmaker";
    public const string Determination = "Determination";
    public const string EideticMemory = "Eidetic Memory";
    public const string EnduringConstitution = "Enduring Constitution";
    public const string EnhancedPhysique = "Enhanced Physique";
    public const string ExtraOccupation = "Extra Occupation";
    public const string ExtraordinaryOrigin = "Extraordinary Origin";
    public const string Famous = "Famous";
    public const string Fearless = "Fearless";
    public const string FirstAid = "First Aid";
    public const string FontOfInformation = "Font of Information";
    public const string FreeRunning = "Free Running";
    public const string FreshEyes = "Fresh Eyes";
    public const string Gearhead = "Gearhead";
    public const string Glibness = "Glibness";
    public const string GodHeritage = "God Heritage";
    public const string Honest = "Honest";
    public const string Interrogation = "Interrogation";
    public const string Inventor = "Inventor";
    public const string Investigation = "Investigation";
    public const string IronWill = "Iron Will";
    public const string LegalEagle = "Legal Eagle";
    public const string Leverage = "Leverage";
    public const string Loner = "Loner";
    public const string Monster = "Monster";
    public const string OutOfShape = "Out of Shape";
    public const string Piloting = "Piloting";
    public const string Pundit = "Pundit";
    public const string Presence = "Presence";
    public const string PublicSpeaking = "Public Speaking";
    public const string QuickLearner = "Quick Learner";
    public const string ScientificExpertise = "Scientific Expertise";
    public const string SignatureAttack = "Signature Attack";
    public const string SituationalAwareness = "Situational Awareness";
    public const string Skeptical = "Skeptical";
    public const string Small = "Small";
    public const string Sneaky = "Sneaky";
    public const string Stranger = "Stranger";
    public const string SurprisingPower = "Surprising Power";
    public const string TechReliance = "Tech Reliance";
    public const string Weakness = "Weakness";
    public const string Weird = "Weird";
}
